language: rust
rust:
  - 1.31.1
  - 1.32.0
  - 1.33.0
  - 1.34.2
  - 1.35.0
  - 1.36.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      os: osx
