language: rust
rust:
  - 1.37.0
  - 1.38.0
  - 1.39.0
  - 1.40.0
  - 1.41.0
  - 1.41.1
  - 1.42.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      os: osx
